# Generated by Django 5.2.12 on 2026-03-18 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0002_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='gemini', max_length=50)),
                ('prompt_sent', models.TextField()),
                ('raw_response', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='quizzes.quiz')),
            ],
            options={
                'db_table': 'ai_generation_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
